config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  get 'random_shot', to:'pages#random_shot'
  get 'know_more', to: 'pages#know_more'
  get 'heavy_stuffs', to: 'pages#heavy_stuffs'
  get 'true_freedom', to: 'pages#true_freedom'
  get 'hazardous_places', to: 'pages#hazardous_places'
  get 'cozy_day', to: 'pages#cozy_day'

  resources :pokemons do
    resources :bookings, only: [ :new, :create, :index, :edit, :update]
  end

  resources :bookings, only: :destroy do
    resources :reviews, only: [ :new, :create, :show ]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :pokemon
  belongs_to :user
  has_one :review

  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end

end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :user
  # has_one :user, through: :booking

  validates :name, :category, :description, :height, :weight, :special_attack, :price_per_day, :health_point, :address, presence: true

  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings

  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  has_one :user, through: :booking

  validates :rating, inclusion: { in: (1..5) }
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :pokemons
  has_many :bookings

  has_one_attached :photo

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :authenticate_user!, except: [ :home, :index ]
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [ :index, :home ], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [ :index, :home ], unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  protected
    def configure_permitted_parameters
      params_to_permit = %i[email password current_password photo first_name last_name user_name]
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(params_to_permit)}
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(params_to_permit)}
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
    @bookings = policy_scope(Booking).order(created_at: :desc)
  end

  def new
    @booking = Booking.new
    @pokemon = Pokemon.find(params[:pokemon_id])
    authorize @pokemon
  end

  def create
    @booking = Booking.new(booking_params)
    @pokemon = Pokemon.find(params[:pokemon_id])
    authorize @booking
    authorize @pokemon
    @booking.user = current_user
    @booking.status = "Pending"
    @booking.pokemon = @pokemon
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @pokemon = @booking.pokemon
    authorize @booking
    authorize @pokemon

    @booking.status =  params[:status][0]

    @pokemon.available = params[:status][1]

    if @booking.save! && @pokemon.save!
      redirect_to dashboard_path(tab: 'content-2')
    else
      render :new
    end

  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to dashboard_path(tab: 'content-2')
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :authenticity_token)
  end

  # def find_pokemon
  #   @pokemon = Pokemon.find(params[:id])
  #   authorize @pokemon
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    @pokemons = Pokemon.where(user: current_user)
    @bookings = Booking.where(user: current_user)
  end

  def random_shot
    @pokemon = Pokemon.where(user: current_user).sample
    redirect_to new_pokemon_booking_path(@pokemon)
    # @pokemons = policy_scope(Pokemon).order(created_at: :desc)
    # @pokemons = Pokemon.sample
  end

  def know_more

  end

  def heavy_stuffs

  end

  def true_freedom

  end

  def hazardous_places

  end

  def cozy_day

  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :find_pokemon, only: [:show, :edit, :update, :destroy]
  def index
    @pokemons = policy_scope(Pokemon).order(created_at: :desc)
    if current_user.nil?
      @pokemons = @pokemons.all
    else
      @pokemons = @pokemons.where.not(user_id: current_user.id)
    end
    @pokemons = @pokemons.where("name ILIKE ?", "%#{params[:pokemon_name]}%") if params[:pokemon_name]
    @pokemons = @pokemons.where("address ILIKE ?", "%#{params[:location]}%") if params[:location]
    @pokemons = @pokemons.where("category ILIKE ?", "%#{params[:category]}%") if params[:category]

    # @pokemons = @pokemons.near(params[:search], 25)
    @markers = @pokemons.geocoded.map do |pokemon|
      {
        lat: pokemon.latitude,
        lng: pokemon.longitude
      }
    end
  end

  def show
  end

  def new
    @pokemon = Pokemon.new
    authorize @pokemon
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    authorize @pokemon
    @pokemon.user = current_user
    if @pokemon.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @pokemon.update(pokemon_params)
    redirect_to pokemon_path
  end

  def destroy
    @pokemon.destroy
    # render json: { message: "Post ##{@pokemon.name} successfully deleted!" }
    # rescue ActiveRecord::RecordNotDestroyed
    redirect_to dashboard_path
  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:photo, :user, :name, :category, :description, :height, :weight, :special_attack, :price_per_day, :health_point, :address)
  end

  def find_pokemon
    @pokemon = Pokemon.find(params[:id])
    authorize @pokemon
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def show

    @pokemon = Pokemon.find(params[:id])
    @reviews = @pokemon.reviews
    authorize @reviews
    authorize @pokemon
  end

  def new
    @review = Review.new
    @booking = Booking.find(params[:booking_id])
    authorize @booking
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @pokemon = @booking.pokemon
    authorize @booking
    authorize @review
    authorize @pokemon
    @review.booking = @booking

    if @review.save
      redirect_to dashboard_path(tab: 'content-2')
    else
      render 'pages/dashboard'
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content, :booking_id, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokeLab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar'  %>
    <% if current_page?("/") %>
      <%= yield %>
    <% else %>
      <div class="custom-container">
        <%= yield %>
      </div>
    <% end %>
    <%= render 'shared/footer'  %>
  </body>
</html>

app/views/pages/cozy_day.html.erb
<div class= "h1-center-title">
  <h1>Your cozy day whit cozy Pokemons</h1>
</div>

app/views/pages/dashboard.html.erb
<div style="background-image: url(<%= image_path 'background_transparent.png'%>)">
  <div class="tabs">
    <div class="tab <%= 'tab-active' if params[:tab] == 'content-1' || params[:tab].nil? %>" id="tab-1">
      <i class="fas fa-list-alt"></i><br>
      My Pokemons
    </div>
    <div class="tab <%= 'tab-active' if params[:tab] == 'content-2' %>" id="tab-2">
      <i class="fas fa-calendar-plus"></i><br>
      My Bookings
    </div>
    <div class="tab <%= 'tab-active' if params[:tab] == 'content-3' %>" id="tab-3">
      <i class="fas fa-star"></i><br>
      My Reviews
    </div>
  </div>

  <div class="container">


    <%# To do : add curent_user name once model updated  %>

  <div class="content <%= (params[:tab] == 'content-1' || params[:tab].nil?) ? 'displayed' : 'hidden' %>" id="content-1">
    <div class="dash-title">
      <h1>Welcome <%= current_user.first_name.capitalize %></h1>
    </div>
    <div class="add-pokemon">
      <%= link_to raw('<p><i class="fas fa-plus"></i> Pokemon</p>'), new_pokemon_path %>
    </div>
    <div class="cards overflow-pokemons">
      <% @pokemons.each do |pokemon| %>
          <div class="card-pokedex clickable">
            <div class="card-buttons">
              <%= link_to raw('<i class="fas fa-trash-alt"></i>'), pokemon_path(pokemon), data: { confirm_swal: '', method: "DELETE"} %>
              <%= link_to raw('<i class="fas fa-edit"></i>'), edit_pokemon_path(pokemon) %>
            </div>
              <%= link_to pokemon_path(pokemon) do %>
                <div class="card-header">
                  <h3><%= pokemon.name.capitalize %></h3>
                  <p><%= pokemon.health_point %>PV
                  <% case pokemon.category %>
                    <% when "Water" %>
                      <span class="font-water"><%= raw('<i class="fas fa-tint"></i>') %></span>
                    <% when "Fire" %>
                      <span class="font-fire"><%= raw('<i class="fas fa-fire"></i>') %></span>
                    <% when "Plant" %>
                      <span class="font-plant"><%= raw('<i class="fas fa-seedling"></i>') %></span>
                    <% when "Earth" %>
                      <span class="font-earth"><%= raw('<i class="fas fa-mountains"></i>')  %></span>
                    <% when "Psych" %>
                      <span class="font-psych"><%= raw('<i class="fas fa-podcast"></i>')  %></span>
                    <% when "Electric" %>
                      <span class="font-electric"></span><%= raw('<i class="fas fa-bolt"></i>') %></span>
                    <% else %>
                    <span class="font-electric"></span><%= raw('<i class="fas fa-bolt"></i>') %></span>
                  <% end %></p>
                </div>
                <div class="image">
                  <% if pokemon.photo.attached? %>
                    <%= cl_image_tag pokemon.photo.key %>
                  <% else %>
                    <%= image_tag "verso-carte.png" %>
                  <% end %>
                </div>
                <div class="card-description">
                  <h5><i class="fas fa-crown"></i> <%= pokemon.special_attack %></h5>
                  <p><%= pokemon.description.truncate(100) %></p>
                </div>
                <div class="card-price">
                  <p><strong><%= pokemon.reviews.average(:rating) %></strong><i class="fas fa-star"> </i><em><%= pokemon.reviews.count %> reviews</em></p>
                  <h5><%= pokemon.price_per_day%>€</h5>
                </div>
              <% end %>
            </div>
        <% end %>
      </div>
    </div>

    <div class="content <%= params[:tab] == 'content-2' ? 'displayed' : 'hidden' %>" id="content-2">
      <div class="d-flex">

        <div class="w-50" >
          <h2 style="background-color: rgba(250, 250, 250, 0.8);width: 400px"> Requests sent</h2>
          <div class="d-flex flex-column over">
            <% Booking.where(user_id: current_user.id).each do |booking| %>
              <div class="card-booking m-4">
                <% if Pokemon.find(booking.pokemon_id).photo.attached? %>
                  <%= cl_image_tag Pokemon.find(booking.pokemon_id).photo.key, class:"pokebook" %>
                <% else %>
                  <%= cl_image_path "default_photo.png", class:"pokebook" %>
                <% end %>
                <div class="booking-content pl-4">
                  <h3><%= Pokemon.find(booking.pokemon_id).name.capitalize %></h3>
                  <div class="from">
                    <h5>At : <%= Pokemon.find(booking.pokemon_id).address %></h5>
                    <p>From : <%= booking.start_date %></p>
                    <p>To : <%= booking.end_date %></p>
                    <p>Duration : <%= (booking.end_date - booking.start_date).to_i %> days</p>
                    <p class="mt-3">Total price : <%= (booking.end_date - booking.start_date).to_i * Pokemon.find(booking.pokemon_id).price_per_day.to_i %> € </p>
                  </div>
                </div>
                <div class="actions-details">
                  <div class="status">
                    <% if booking.status == "Confirmed"%>
                      <i class="fas fa-check-circle"></i>
                      <% if booking.review == nil %>
                        <div class="add-review">
                          <%= link_to raw('<i class="fas fa-plus"></i> review'), new_booking_review_path(booking) %>
                        </div>
                      <% end %>
                    <% elsif booking.status == "Denied"%>
                      <i class="far fa-times-circle"></i>
                    <% else %>
                      <i class="far fa-question-circle"></i>
                    <% end %>
                  </div>

                <div class="book-actions">
                  <%= link_to raw('<i class="fas fa-trash-alt"></i>'), booking_path(booking), method: :delete, data: { confirm_swal: '', method: "DELETE"}  %>
                <%# </div> %>
              </div>
            <% end %>
          </div>
        </div>

        <div class="w-50" >
          <h2 style="background-color: rgba(250, 250, 250, 0.8);width: 400px">Requests received</h2>
          <div class="d-flex flex-column over">
            <% other_bookings = [] %>
            <% Booking.all.each { |b| other_bookings << b if b.pokemon.user_id == current_user.id } %>
            <% other_bookings.each do |booking| %>
              <div class="card-booking m-4">
                <% if Pokemon.find(booking.pokemon_id).photo.attached? %>
                  <%= cl_image_tag Pokemon.find(booking.pokemon_id).photo.key, class:"pokebook" %>
                <% else %>
                  <%= cl_image_path "default_photo.png", class:"pokebook" %>
                <% end %>
                <div class="booking-content pl-4">
                  <h3><%= Pokemon.find(booking.pokemon_id).name%></h3>
                  <div class="from">
                    <h5>At : <%= Pokemon.find(booking.pokemon_id).address %></h5>
                    <p>From : <%= booking.start_date %></p>
                    <p>To : <%= booking.end_date %></p>
                    <p>Duration : <%= (booking.end_date - booking.start_date).to_i %> days</p>
                    <p class="mt-3">Total price : <%= (booking.end_date - booking.start_date).to_i * Pokemon.find(booking.pokemon_id).price_per_day.to_i %> € </p>
                  </div>
                </div>

              </div>
              <div class="actions-details">
                <div class="status">
                  <% if booking.status == "Confirmed"%>
                    <i class="fas fa-check-circle"></i><br>
                  <% elsif booking.status == "Denied"%>
                    <i class="far fa-times-circle"></i>
                  <% else %>
                    <i class="far fa-question-circle"></i>
                  <% end %>
                </div>
                <div class="book-actions">
                  <% if booking.status == "Pending"%>
                    <%= link_to raw('<i class="fas fa-check-circle"></i>'), pokemon_booking_path(Pokemon.find(booking.pokemon_id).id, booking, status: ["Confirmed", false]), method: :patch, data: { confirm: "Are you sure?" } %>
                    <%= link_to raw('<i class="far fa-times-circle"></i>'), pokemon_booking_path(Pokemon.find(booking.pokemon_id).id, booking, status: ["Denied", true]), method: :patch, data: { confirm: "Are you sure?" } %>
                    <%= link_to raw('<i class="fas fa-trash-alt"></i>'), booking_path(booking), data: { confirm_swal: '', method: "DELETE"} %>
                  <% else %>
                    <%= link_to raw('<i class="fas fa-trash-alt"></i>'), booking_path(booking), data: { confirm_swal: '', method: "DELETE"} %>
                  <% end %>

                <div class="actions-details">
                  <div class="status">
                    <% if booking.status == "Confirmed"%>
                      <i class="fas fa-check-circle"></i><br>
                      <% if booking.review == nil %>
                        <div class="add-review">
                          <%= link_to raw('<i class="fas fa-plus"></i> review'), new_booking_review_path(booking) %>
                        </div>
                      <% end %>
                    <% elsif booking.status == "Denied"%>
                      <i class="far fa-times-circle"></i>
                    <% else %>
                      <i class="far fa-question-circle"></i>
                    <% end %>
                  </div>
                  <div class="book-actions">
                    <% if booking.status == "Pending"%>
                      <%= link_to raw('<i class="fas fa-check-circle"></i>'), pokemon_booking_path(Pokemon.find(booking.pokemon_id).id, booking, status: ["Confirmed", false]), method: :patch, data: { confirm: "Are you sure?" } %>
                      <%= link_to raw('<i class="far fa-times-circle"></i>'), pokemon_booking_path(Pokemon.find(booking.pokemon_id).id, booking, status: ["Denied", true]), method: :patch, data: { confirm: "Are you sure?" } %>
                      <%= link_to raw('<i class="fas fa-trash-alt"></i>'), booking_path(booking), data: { confirm_swal: '', method: "DELETE"} %>
                    <% else %>
                      <%= link_to raw('<i class="fas fa-trash-alt"></i>'), booking_path(booking), data: { confirm_swal: '', method: "DELETE"} %>
                    <% end %>
                  </div>

                </div>
              </div>
            <% end %>
          </div>
        </div>
      
      </div>
    </div>

    <div class="content  <%= params[:tab] == 'content-3' ? 'displayed' : 'hidden' %>" id="content-3">
      <div class="dash-title">
        <h1>Welcome <%= current_user.first_name %></h1>
      </div>
      <h2 style="background-color: rgba(250, 250, 250, 0.8);width: 400px;text-align: center">Your Pokemons reviews</h2>
      <div class="card-reviews">
        <% @pokemons.each do |pokemon| %>
          <% if pokemon.reviews.length > 0 %>
            <div class="card-review">
              <div class="image">
                <% if pokemon.photo.attached? %>
                  <%= cl_image_tag pokemon.photo.key %>
                <% else %>
                  <%= image_tag "verso-carte.png" %>
                <% end %>
              </div>
              <div class="review-content">
                <h3><%= pokemon.name.capitalize  %></h3>
                <% reviews = pokemon.reviews  %>
                <% reviews.each do |review| %>
                  <p><strong><%= review.rating  %></strong><i class="fas fa-star"></i>
                  <i class="fas fa-quote-left">    </i><strong><%= review.comment %></strong>  <i class="fas fa-quote-right"></i> left by: <em><%= review.booking.user.first_name  %> <%= review.booking.user.last_name  %></em></p>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/hazardous_places.html.erb
<div class= "h1-center-title">
  <h1>Travel and think about anything</h1>
</div>

app/views/pages/heavy_stuffs.html.erb
<div class= "h1-center-title">
  <h1>They can help you with your heavy stuffs</h1>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="form-home">
    <%= render "shared/search_form" %>
  </div>
  <%= link_to("Get a random Pokemon", random_shot_path, { class: 'btn btn-shoot' }) %>
  <i class="fas fa-arrow-down"></i>
</div>

<div class="container-home">
  <div class="cards">
    <div class="home-card lifting-card">
      <p><%= link_to "Help you with heavy stuffs", heavy_stuffs_path %></p>
      <hr>
    </div>
    <div class="home-card flying-card">
      <p><%= link_to "Enjoy true freedom", true_freedom_path %></p>
      <hr>
    </div>
    <div class="home-card travelling-card">
      <p><%= link_to "Travel in hazardous places", hazardous_places_path %></p>
      <hr>
      </div>
    <div class="home-card sleeping-card">
      <p><%= link_to "Just enjoy a cozy day", cozy_day_path %></p>
      <hr>
    </div>
  </div>

  <div class="card-owner">
    <h2>Rent your Pokemon</h2>
    <p>Earn money, help the community, allow your pokemon to enjoy new adventures</p>
    <button class="btn btn-know-more "><%= link_to "Know more", know_more_path %></button>
  </div>
</div>

app/views/pages/random_shot.html.erb
  <div class= "h1-center-title">
    <h1>Your Random Pokemon</h1>
  </div>

app/views/pages/true_freedom.html.erb
<div class= "h1-center-title">
  <h1>You can travel all around the world</h1>
</div>

app/views/pokemons/new.html.erb
<div class="btn-return">
  <%= link_to raw('<i class="fas fa-arrow-left"></i>'), dashboard_path %>
</div>

<div class="mt-5 col-4 offset-4">

  <h1>Add New Pokemon</h1>

  <%= simple_form_for(@pokemon) do |f| %>
  <%= f.input :name %>
  <%= f.input :category, collection: ["Electric","Fire","Earth","Psych","Plant","Water"] %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :height, label: "Height (m)"%>
  <%= f.input :weight, label: "Weight (kg)" %>
  <%= f.input :special_attack %>
  <%= f.input :price_per_day, label: "Price per day (€)" %>
  <%= f.input :health_point %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Add New Pokemon", class: "btn btn-primary mt-5" %>
  <% end %>

</div>

<div class="btn-container mt-5 col-4 offset-4">
  <p><%= link_to "Return to list", pokemons_path, class: "btn btn-primary"  %></p>
</div>

app/views/pokemons/show.html.erb
<div class="container-show">
  <div class="card-show-all">

    <div class = "cards-left">
      <div class="pokemon-card">
        <div class = "card-image">
          <% if @pokemon.photo.attached? %>
            <%= cl_image_tag @pokemon.photo.key, width: 250, height: 300, crop: :fill %>
          <% else %>
            <%= cl_image_tag("tfoqtj3tttbjd0satx2t", width: 250, height: 300, crop: :fill) %>
          <% end %>
        </div>
        <div class="pokemon-description">
          <p><%= @pokemon.description %></p>
        </div>
      </div>
      <div class="button-all-down">
        <div class= "button-blue"></div>
        <div class= "button-green"></div>
        <div class= "button-orange"></div>
        <div class= "button-grey"></div>
      </div>
    </div>


    <div class = "cards-right">
        <h2><%= @pokemon.name.capitalize %></h2>

        <%if @pokemon.category == "Electric"%>
          <div class="electric">
        <%elsif @pokemon.category == "Fire"%>
          <div class="fire">
        <%elsif @pokemon.category == "Earth"%>
          <div class="earth">
        <%elsif @pokemon.category == "Psych"%>
          <div class="psych">
        <%elsif @pokemon.category == "Plant"%>
          <div class="plant">
        <%else%>
          <div class="water">
        <%end%>

            <div class="details">
                <div class= "detail-left">
                  <p><strong>Category</strong> : <%=@pokemon.category%></p>
                  <p><strong>Height</strong> : <%= @pokemon.height %> m</p>
                  <p><strong>Weight</strong> : <%= @pokemon.weight %> kg</p>
                </div>
                <div class = "detail-right">
                  <p><strong>Special Attack</strong> : <%= @pokemon.special_attack %></p>
                  <p><strong>Price per day</strong> : <%= @pokemon.price_per_day %> €</p>
                  <p><strong>Health Points</strong> : <%= @pokemon.health_point %></p>
                </div>
              </div>
          </div>
          <div class="show-button">
            <p><%= link_to raw('<i class="fas fa-arrow-left"></i>'), dashboard_path %></p>
            <p><%= link_to raw('<i class="fas fa-edit"></i>'), edit_pokemon_path(@pokemon) %></p>
            <p><%= link_to raw('<i class="fas fa-trash-alt"></i>'), pokemon_path(@pokemon), method: :delete, data: { confirm: "Are you sure?" } %></p>
          </div>
          <div class="button-to-reviews">
            <%= link_to "Go see the reviews",  booking_review_path(@pokemon) %>
          </div>

    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<% if current_page?("/") %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
<% else %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-lewagon-white">
<% end %>

  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "pokeball-logo.png", class:"logo" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <%# <li class="nav-item active"> %>
          <%#= link_to "Home", root_path, class: "nav-link" %>
        <%# </li> %>
        <%# <li class="nav-item"> %>
          <%#= link_to "Messages", "#", class: "nav-link" %>
        <%# </li> %>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <%else%>
            <%= image_tag "default_photo.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <%end%>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "New Pokemon", new_pokemon_path, class: "dropdown-item" %>
            <%= link_to "My Pokemons", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Rent a Pokemon", pokemons_path, class: "dropdown-item", location: "" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link", id: "login" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>